name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Primary]
    types: [completed]
    branches: [main]
  push:
    tags: ["v*"]

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  deploy:
    uses: orcastration-ai/.github/.github/workflows/deploy-static-site.yml@main
    with:
      site-id: docs-orcastration-ai
